config/routes.rb
Rails.application.routes.draw do

  get 'tests/test1'
  get 'tests/test2'
  get 'tests/test3'
  root to: 'users#top'
  devise_for :admins
  devise_for :users
  get 'admins/top' => 'admins#top'
  get 'about/top' => 'about#top'
  resources :genres
  resources :articles
  resources :notices
  resources :contacts
  get 'users/top' => 'users#top'
  resources :users, only: [:index, :show, :edit, :update]
  resources :comments, only: [:create, :destroy]
  resources :favgenres, only: [:create, :destroy]
  resources :favarticles, only: [:create, :destroy]
  get 'tests/test1' => 'tests#test1', as: 'test1'
  get 'tests/test2' => 'tests#test2', as: 'test2'
  get 'tests/test3' => 'tests#test3', as: 'test3'
  get 'versions/0_1_1' => 'versions#ver0_1_1', as: 'v0_1_1'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :genre
  has_many :favarticles, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  attachment :image
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :user
end

app/models/favarticle.rb
class Favarticle < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/favgenre.rb
class Favgenre < ApplicationRecord
  belongs_to :user
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
  belongs_to :user
  has_many :articles, dependent: :destroy
  has_many :favgenres, dependent: :destroy

  validates :name, length: { in: 1..10 }, uniqueness: true
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favgenres, dependent: :destroy
  has_many :favarticles, dependent: :destroy
  has_many :genres
  has_many :articles, dependent: :destroy
  has_many :contact
  attachment :image
end

app/models/version.rb
class Version < ApplicationRecord
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :authenticate_admin!, only:[:new, :edit, :create, :destroy]

  def index
    @notices = Notice.all.order(created_at: :desc)
  end

  def show
    @notice = Notice.find(params[:id])
  end

  def edit
    @notice = Notice.find(params[:id])
  end

  def new
    @notice = Notice.new
    @notices = Notice.all.order(created_at: :desc)
  end

  def update
    notice = Notice.find(params[:id])
    if notice.update(notice_params)
      redirect_to new_notice_path, notice: "お知らせの更新に成功しました"
    else
      render action: :edit
    end
  end

  def create
    notice = Notice.new(notice_params)
    if notice.save
      redirect_to notices_path, notice: '新規お知らせの投稿が完了しました。'
    else
      render action: :new
    end
  end

  def destroy
    notice = Notice.find(params[:id])
    notice.destroy
    redirect_to new_notice_path, notice: "削除に成功しました！"
  end

  private
  def notice_params
    params.require(:notice).permit(:introduction)
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/favgenres_helper.rb
module FavgenresHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/notices/edit.html.erb
<div class="row">
	<div class="col-xs-1"></div>
	<div class="col-xs-11">
		<h2>お知らせ編集</h2>
		<%= form_with model: @notice do |f| %>
			<div class="row br50">
				<div class="col-xs-1">
					<%= f.label :introduction, "お知らせ内容" %>
				</div>
				<div class="col-xs-2">
					<%= f.text_field :introduction %>
				</div>
				<div class="col-xs-1">
					<%= f.submit "更新", class: "btn btn-success" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/notices/index.html.erb
<h1>管理者からのお知らせ</h1>

<table class="table">
	<tr>
		<th class="col-xs-3">お知らせ日時</th>
		<th class="col-xs-1"></th>
		<th class="col-xs-8">お知らせ内容</th>
	</tr>
<% @notices.each do |notice| %>
	<tr>
		<td class="col-xs-3">
			<% if notice.updated_at.present? %>
				<%= notice.updated_at.to_s(:datetime_jp) %>
			<% else %>
				<%= notice.created_at.to_s(:datetime_jp) %>
			<% end %>
		</td>
		<td class="col-xs-1">
			<% if notice.updated_at.present? %>
				<% notice_time = notice.updated_at %>
			<% else %>
				<% notice_time = notice.created_at %>
			<% end %>

			<% if Time.now < notice_time + 86400 %>
				<p class="notice_index_new1">NEW</p>
			<% elsif Time.now < notice_time + 604800 %>
				<p class="notice_index_new2">NEW</p>
			<% else %>

			<% end %>
		</td>
		<td class="col-xs-8">
			<%= notice.introduction %>
		</td>
	</tr>
<% end %>
</table>

app/views/notices/new.html.erb
<h1>新規お知らせ作成</h1>
<%= form_with model: @notice do |f| %>
<div class="row br50">
	<div class="col-xs-1"></div>
	<div class="col-xs-6">
		<div class="row">
			<div class="col-xs-2">
				<%= f.label :introduction, "お知らせ内容" %>
			</div>
			<div class="col-xs-3">
				<%= f.text_field :introduction %>
			</div>

			<div class="col-xs-2">
				<%= f.submit "投稿", class: "btn btn-success" %>
			</div>
		</div>
	</div>
	<div class="col-xs-5">
		<h2>実際のお知らせ見た目</h2>
		<table class="table">
			<tr>
				<th class="col-xs-3">お知らせ日時</th>
				<th class="col-xs-1"></th>
				<th class="col-xs-6">お知らせ内容</th>
				<th class="col-xs-1"></th>
				<th class="col-xs-1"></th>
			</tr>
		<% @notices.each do |notice| %>
			<tr>
				<td class="col-xs-3">
					<% if notice.updated_at.present? %>
						<%= notice.updated_at.to_s(:datetime_jp) %>
					<% else %>
						<%= notice.created_at.to_s(:datetime_jp) %>
					<% end %>
				</td>
				<td class="col-xs-1">
					<% if notice.updated_at.present? %>
						<% notice_time = notice.updated_at %>
					<% else %>
						<% notice_time = notice.created_at %>
					<% end %>

					<% if Time.now < notice_time + 86400 %>
						<p class="notice_index_new1">NEW</p>
					<% elsif Time.now < notice_time + 604800 %>
						<p class="notice_index_new2">NEW</p>
					<% else %>

					<% end %>
				</td>
				<td class="col-xs-6">
					<%= notice.introduction %>
				</td>
				<td class="col-xs-1">
					<%= link_to "編集", edit_notice_path(notice.id), class: "btn btn-success", data: { confirm: "新規投稿に入力中の内容が消えます。" } %>
				</td>
				<td class="col-xs-1">
					<%= link_to "削除", notice_path(notice.id), method: :delete, class: "btn btn-danger", data: { confirm: "削除します。よろしいですか？" } %>
			</tr>
		<% end %>
		</table>
	</div>
</div>


<% end %>

app/views/notices/show.html.erb
<div>
	<h2><%= @notice.introduction %></h2>
</div>