config/routes.rb
Rails.application.routes.draw do

  get 'tests/test1'
  get 'tests/test2'
  get 'tests/test3'
  root to: 'users#top'
  devise_for :admins
  devise_for :users
  get 'admins/top' => 'admins#top'
  get 'about/top' => 'about#top'
  resources :genres
  resources :articles
  resources :notices
  resources :contacts
  get 'users/top' => 'users#top'
  resources :users, only: [:index, :show, :edit, :update]
  resources :comments, only: [:create, :destroy]
  resources :favgenres, only: [:create, :destroy]
  resources :favarticles, only: [:create, :destroy]
  get 'tests/test1' => 'tests#test1', as: 'test1'
  get 'tests/test2' => 'tests#test2', as: 'test2'
  get 'tests/test3' => 'tests#test3', as: 'test3'
  get 'versions/0_1_1' => 'versions#ver0_1_1', as: 'v0_1_1'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :genre
  has_many :favarticles, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  attachment :image
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :user
end

app/models/favarticle.rb
class Favarticle < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/favgenre.rb
class Favgenre < ApplicationRecord
  belongs_to :user
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
  belongs_to :user
  has_many :articles, dependent: :destroy
  has_many :favgenres, dependent: :destroy

  validates :name, length: { in: 1..10 }, uniqueness: true
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favgenres, dependent: :destroy
  has_many :favarticles, dependent: :destroy
  has_many :genres
  has_many :articles, dependent: :destroy
  has_many :contact
  attachment :image
end

app/models/version.rb
class Version < ApplicationRecord
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/admins/top.html.erb
<h1>管理者用管理画面</h1>

<% if params[:contact_page].present? %>
<details open>
<% else %>
<details>
<% end %>
	<summary>お問合せ一覧</summary>
	<div class="row">
		<div class="col-xs-1"></div>
		<div class="col-xs-10">
			<table class="table br20">
				<tr>
					<th class="col-xs-2">ユーザー</th>
					<th class="col-xs-3">内容</th>
					<th class="col-xs-2">ボタン</th>
				</tr>
				<% @contacts.each do |contact| %>
				<tr>
					<td><%= link_to contact.user.name, contact_path(contact.user.id) %></td>
					<td><%= link_to contact.title, contact_path(contact.id) %></td>
					<td><%= link_to "削除", contact_path(contact.id), method: :delete, class: "btn btn-danger" %>
				</tr>
				<% end %>
			</table>
			<div class="row">
				<div class="col-xs-4"></div>
				<div class="col-xs-8">
					<%= paginate @contacts, param_name: "contact_page" %>
				</div>
			</div>
		</div>
</details>

<% if params[:genre_page].present? %>
<details open class="br20">
<% else %>
<details class="br20">
<% end %>
	<summary>ジャンル一覧</summary>
	<div class="row">
		<div class="col-xs-1"></div>
		<div class="col-xs-10">
			<table class="table br20">
				<tr>
					<th class="col-xs-2">ジャンル名</th>
					<th class="col-xs-3">ジャンル登録者</th>
					<th class="col-xs-2"></th>
				</tr>
			<% @genres.each do |genre| %>
				<tr>
					<td><%= link_to genre.name, genre_path(genre.id) %></td>
					<td><%= link_to genre.user.name, user_path(genre.user.id) %></td>
					<td><%= link_to "ジャンル削除", user_path(genre.user.id), method: :delete, class: "btn btn-danger", data: { confirm: "本当に消しますか？" } %></td>
				</tr>
			<% end %>
			</table>
			<div class="row">
				<div class="col-xs-4"></div>
				<div class="col-xs-8">
					<%= paginate @genres, param_name: "genre_page" %>
				</div>
			</div>
		</div>
	</div>
</details>

<% if params[:article_page].present? %>
<details open class="br20">
<% else %>
<details class="br20">
<% end %>
	<summary>記事一覧</summary>
	<div class="row">
		<div class="col-xs-1"></div>
		<div class="col-xs-10">
			<table class="table br20">
				<tr>
					<th class="col-xs-2">記事名</th>
					<th class="col-xs-3">記事ジャンル</th>
					<th class="col-xs-2"></th>
				</tr>
				<% @articles.each do |article| %>
				<tr>
					<td><%= link_to article.title, article_path(article.id) %></td>
					<td><%= link_to article.genre.name, genre_path(article.genre.id) %></td>
					<td><%= link_to "記事削除", article_path(article.id), method: :delete, class: "btn btn-danger", data: { confirm: "本当に消しますか？" } %></td>
				</tr>
				<% end %>
			</table>
			<div class="row">
				<div class="col-xs-4"></div>
				<div class="col-xs-8">
					<%= paginate @articles, param_name: "article_page" %>
				</div>
			</div>
		</div>
	</div>
</details>

<% if params[:user_page].present? %>
<details open class="br20">
<% else %>
<details class="br20">
<% end %>
	<summary>新規ユーザー</summary>
	<div class="row">
		<div class="col-xs-1"></div>
		<div class="col-xs-10">
			<table class="table br20">
				<tr>
					<th class="col-xs-2">ユーザー名</th>
					<th class="col-xs-2"></th>
				</tr>
				<% @users.each do |user| %>
				<tr>
					<td><%= user.name %></td>
					<td><%= link_to "削除", user_registration_path, method: :delete, class: "btn btn-danger", data: { confirm: "本当に消しますか？" } %>
					</td>
				</tr>
				<% end %>
			</table>
			<div class="row">
				<div class="col-xs-4"></div>
				<div class="col-xs-8">
					<%= paginate @users, param_name: "user_page" %>
				</div>
			</div>
		</div>
</details>

app/views/shared/_50search.html.erb
<div class="row">
	<h3><%= f.label :genre_50search, "50音検索" %></h3>
</div>
<div class="row">
	<div class="col-xs-1"></div>
	<div class="col-xs-11">
		<%= f.select :genre_50search, {
			'あ': 'あ',
			'い': 'い',
			'う': 'う',
			'え': 'え',
			'お': 'お',
			'か': 'か',
			'き': 'き',
			'く': 'く',
			'け': 'け',
			'こ': 'こ',
		}, { include_blank: '選択してください'}, { class: '50form' } %>
	</div>
</div>
<div class="row">
	<%= f.submit "検索", class: "btn btn-success" %>
</div>

app/views/shared/_header1.html.erb
<header>
  <div class="row">
    <div class="col-xs-3">
      <p class="first_text_style color_white header_line_height">インシンマーレ</p>
    </div>
    <div class="col-xs-9">
      <div class="row">
        <div class="col-xs-2 header_line_height">
          <p class="first_text_style">
            <%= link_to "トップに戻る", root_path, class: "header_text_style" %>
          </p>
        </div>
        <div class="col-xs-2 header_line_height">
          <p class="first_text_style">
            <%= link_to "新規登録", new_user_registration_path, class: "header_text_style" %>
          </p>
        </div>

        <div class="col-xs-2 header_line_height">
          <p class="first_text_style">
            <%= link_to "ログイン", new_user_session_path, class: "header_text_style" %>
          </p>
        </div>

        <div class="col-xs-3 header_line_height">
          <p class="first_text_style">
            <%= link_to "お知らせ", notices_path, class: "header_text_style" %>
          </p>
        </div>

        <div class="col-xs-2 header_line_height">
          <p class="first_text_style">
            <%= link_to "新規記事投稿", new_article_path, class: "header_text_style" %>
          </p>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_header2.html.erb
<header class="container-fluid">
  <div class="row">
    <div class="col-xs-2">
      <p class="first_text_style color_white header_line_height">インシンマーレ</p>
    </div>
    <div class="col-xs-10">
      <div class="row">
        <div class="col-xs-2 header_line_height">
          <p class="first_text_style"><%= link_to "新規記事投稿", new_article_path, class: "header_text_style" %></p>
        </div>

        <div class="col-xs-2 header_line_height">
          <p class="first_text_style"><%= link_to "新規シュミ投稿", new_genre_path, class: "header_text_style" %></p>
        </div>

        <div class="col-xs-2 header_line_height">
          <p class="first_text_style"><%= link_to "お知らせ", notices_path, class: "header_text_style" %></p>
        </div>

        <div class="col-xs-2 header_line_height">
          <p class="first_text_style"><%= link_to "トップページ", root_path, class: "header_text_style" %></p>
        </div>

        <div class="col-xs-2 header_line_height">
          <p class="first_text_style"><%= link_to "マイページ", user_path(current_user), class: "header_text_style" %></p>
        </div>

        <div class="col-xs-2 header_line_height">
          <p class="first_text_style"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header_text_style" %></p>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_header_admin.html.erb
<header class="container-fluid">
  <div class="row">
    <div class="col-xs-3">
      <p class="first_text_style color_white header_line_height">インシンマーレ</p>
    </div>
    <div class="col-xs-9">
      <div class="row">
        <div class="col-xs-3 header_line_height">
          <p class="first_text_style">
            <%= link_to "お知らせ投稿", new_notice_path, class: "header_text_style" %>
          </p>
        </div>

        <div class="col-xs-3">
        </div>

        <div class="col-xs-3 header_line_height">
          <p class="first_text_style">
            <%= link_to "管理者トップへ", admins_top_path, class: "header_text_style" %>
          </p>
        </div>

        <div class="col-xs-3 header_line_height">
          <p class="first_text_style">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "header_text_style" %>
          </p>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_header_article.html.erb
<header class="container-fluid">
  <div class="row">
    <div class="col-xs-3">
      <p class="first_text_style color_white header_line_height">インシンマーレ</p>
    </div>
    <div class="col-xs-9">
      <div class="row">
        <div class="col-xs-3 btn_header_position">
        <% if user_signed_in? %>
          <% if @favarticle.id.present? %>
            <%= link_to "★お気に入り中", favarticle_path(@favarticle.id), method: :delete, class: "btn btn-primary" %>
          <% else %>
            <%= form_with model: @favarticle, url: { controller: "favarticles", action: "create"} do |f| %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.hidden_field :article_id, :value => @article.id %>
            <%= f.submit "☆お気に入りに登録", class: "btn btn-info" %>
            <% end %>
          <% end %>
        <% end %>
        </div>

        <div class="col-xs-3 header_line_height">
          <p class="first_text_style">
            <%= link_to "トップに戻る", root_path, class: "header_text_style" %>
          </p>
        </div>

        <div class="col-xs-3 header_line_height">
          <p class="first_text_style">
            <%= link_to "マイページ", user_path(current_user), class: "header_text_style" %>
          </p>
        </div>

        <div class="col-xs-3">
          <p class="first_text_style header_line_height">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header_text_style" %>
          </p>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_header_genre.html.erb
<header class="container-fluid">
  <div class="row">
    <div class="col-xs-3">
      <p class="first_text_style color_white header_line_height">インシンマーレ</p>
    </div>
    <div class="col-xs-9">
      <div class="row">
        <div class="col-xs-3 btn_header_position">
        <% if user_signed_in? %>
          <% if @favgenre.id.present? %>
            <%= link_to "★お気に入り中", favgenre_path(@favgenre.id), method: :delete, class: "btn btn-primary" %>
          <% else %>
            <%= form_with model: @favgenre, url: { controller: "favgenres", action: "create"} do |f| %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.hidden_field :genre_id, :value => @genre.id %>
            <%= f.submit "☆お気に入りに登録", class: "btn btn-info" %>
            <% end %>
          <% end %>
        <% end %>

        </div>

        <div class="col-xs-3 header_line_height">
          <p class="first_text_style">
            <%= link_to "トップに戻る", root_path, class: "header_text_style" %>
          </p>
        </div>

        <div class="col-xs-3 header_line_height">
          <p class="first_text_style">
            <%= link_to "マイページ", user_path(current_user), class: "header_text_style" %>
          </p>
        </div>

        <div class="col-xs-3 header_line_height">
          <p class="first_text_style">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header_text_style" %>
          </p>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_how_to_do.html.erb
<div class="row">
	<div class="col-xs-11">
	</div>
</div>

app/views/shared/_side_genre.html.erb
<div class="row">
	<div class="col-xs-1"></div>
	<div class="col-xs-11">
		<h3>ジャンルの検索</h3>
		<p class="font12">※ひらがなで部分一致検索できます</p>
	</div>
</div>
<div class="br20"></div>
<details>
	<summary>ひらがな検索</summary>
	<div class="br20"></div>
	<%= form_with url: articles_path, method: :get, local: true do |f| %>
	<div class="row">
		<div class="col-xs-2">
			<%= f.label :genre_search, "検索" %>
		</div>
		<div class="col-xs-6">
			<%= f.text_field :genre_search %>
		</div>
		<div class="col-xs-2">
			<%= f.submit "検索", class: "btn btn-success" %>
		</div>
	</div>
	<% end %>
</details>
<div class="row">
	<% if params[:genre_search].present? %>
		<h3 class="col-xs-12">"<%= params[:genre_search] %>"の検索結果</h3>
	<% else %>
		<h3 class="col-xs-12">ジャンル一覧</h3>
	<% end %>
</div>
<div class="br20"></div>
<% @genres.each do |genre| %>
	<div class="row">
		<div class="col-xs-1"></div>
		<div class="col-xs-1">
			<span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
		</div>
		<div class="col-xs-9">
			<p class="font16">
				<%= link_to genre.name, articles_path(:gen => genre.id) %>
			</p>
		</div>
	</div>
<% end %>

app/views/shared/_test_linker.html.erb
<h1>Test linker</h1>
<ul>
	<li><%= link_to "ABOUT", about_top_path %></li>
	<li><%= link_to "ADMIN_LOGIN", new_admin_session_path %></li>
	<li><%= link_to "GENRE_INDEX", genres_path %></li>
	<li><%= link_to "NEW_GENRE", new_genre_path %></li>
	<li><%= link_to "ARTICLE_INDEX", articles_path %></li>
	<li><%= link_to "NEW_ARTICLE", new_article_path %></li>
	<li><%= link_to "NOTICE_INDEX", notices_path %></li>
	<li><%= link_to "NEW_NOTICE", new_notice_path %></li>
	<li><%= link_to "USER_INDEX", users_path %></li>
	<li><%= link_to "TOP", users_top_path %></li>
	<li><%= link_to "USER_SIGN_IN", new_user_session_path %></li>
	<li><%= link_to "USER_SIGN_UP", new_user_registration_path %></li>
	<li><%= link_to "CONTACT_US", new_contact_path %></li>
</ul>

app/views/shared/_user_info.html.erb
<div class="row">
	<div class="col-xs-1"></div>
	<div class="col-xs-11 img_area_200">
		<% if @user.image_id.present? %>
			<%= attachment_image_tag :image, :fill, 200, 200, format: "jpg", class: "image_radius" %>
		<% else %>
			<%= image_tag "/images/no_img.png" %>
		<% end %>
	</div>
</div>

<div class="row">
	<div class="col-xs-1"></div>
	<div class="col-xs-11">
		<% if @user.introduction.present? %>
			<%= @user.introduction %>
		<% else %>
			<p>自己紹介無し（プロフィールの変更から編集できます。)</p>
		<% end %>
	</div>
</div>

<div class="row under_border br20">
	<div class="col-xs-1"></div>
	<div class="col-xs-11">
		<h3><span class="glyphicon glyphicon-edit" aria-hidden="true"></span><%= link_to "プロフィールの変更", edit_user_path(@user.id) %></h3>
	</div>
</div>

<div class="row under_border">
	<div class="col-xs-1"></div>
	<div class="col-xs-11">
		<h3><span class="glyphicon glyphicon-share" aria-hidden="true"></span><%= link_to " ログアウト", destroy_user_session_path, method: :delete %></h3>
	</div>
</div>

<div class="row br20">
	<div class="col-xs-1"></div>
	<div class="col-xs-11">
		<h3><span class="glyphicon glyphicon-link" aria-hidden="true"></span>　リンク</h3>
	</div>
</div>

<div class="row br20">
	<div class="col-xs-1"></div>
	<div class="col-xs-11">
		<table class="table">
			<tr>
				<th class="col-xs-12">お気に入りジャンル</th>
			</tr>
			<% @favgenres.each do |fg| %>
			<tr>
				<td class="col-xs-12">
					<%= link_to fg.genre.name, genre_path(fg.genre.id) %>
				</td>
			</tr>
			<% end %>
		</table>
	</div>
</div>

<div class="row br20">
	<div class="col-xs-1"></div>
	<div class="col-xs-11">
		<table class="table">
			<tr>
				<th class="col-xs-12">お気に入り記事</th>
			</tr>
			<% @favarticles.each do |fa| %>
			<tr>
				<td class="col-xs-12">
					<%= link_to fa.article.title, article_path(fa.article.id) %>
				</td>
			</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/ver/ver_0_1_0.html.erb
<div class="row top_side_bar">
	<div class="col-xs-3">
		<div class="row top_left_about">
			<p class="first_text_style"><%= link_to "このサイトについて", about_top_path, class: "color_white" %></p>
		</div>
		<div class="row top_left_top5 color_white">
			<div class="col-xs-1">
			</div>
			<p class="font16 first_text_style"><b>シュミいいねランキング</b></p>
			<div class="col-xs-1">
			</div>
			<div class="col-xs-11">
				<table class="table">
					<tr>
						<th class="col-xs-1">順位</th>
						<th class="col-xs-3">シュミ名</th>
						<th class="col-xs-2">いいね数</th>
					</tr>
				<% @genres_rank.each_with_index do |genre, rank| %>
					<tr>
						<th class="col-xs-1"><%= rank + 1 %></th>
						<th class="col-xs-3">
							<%=link_to genre.name[0...10], genre_path(genre.id), class: "color_white" %>
						</th>
						<th class="col-xs-2">
							<p><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>  <%= genre.favgenres.all.count %></p>
						</th>
					</tr>
				<% end %>
				</table>
			</div>
		</div>
		<div class="row top_left_genre color_white pad20">
			<div class="col-xs-1"></div>
			<div class="col-xs-11">
				<table class="table">
					<tr>
						<th class="col-xs-12">
							<h4>ランダムシュミ一覧</h4>
						</th>
					</tr>
					<% @genres_random.each do |genre| %>
						<tr>
							<td class="col-xs-12"><span class="glyphicon glyphicon-tag" aria-hidden="true"></span>　<%= link_to genre.name, genre_path(genre.id), class: "color_white" %></td>
						</tr>
					<% end %>
				</table>
			</div>
		</div>
	</div>

	<div class="col-xs-9 top_main">
		<div class="col-xs-1"></div>
		<div class="col-xs-11">
			<div class="top_notice_table">
				<table class="table">
					<tr>
						<th>お知らせ一覧</th>
						<th></th>
					</tr>
					<% @notices.each do |notice| %>
					<tr>
						<td><%= notice.created_at.to_s(:datetime_jp) %>
						<td><%= link_to notice.introduction, notice_path(notice.id) %></td>
					</tr>
					<% end %>
				</table>
				<div class="pad_left_20">
					<%= link_to "お知らせ一覧へ", notices_path %>
				</div>
			</div>

			<script type="text/python" src="/pyth/test.py"></script>
			<script>
				$(document).ready(function(){
					$('img[usemap]').rwdImageMaps();
				});
			</script>
			<div classs="row main_genre_map">
				<%= image_tag "/images/mangapoi.png", usemap: "#manga" %>
				<map name="manga">
					<area shape="rect" coords="586,503,881,664" href="/articles" alt="">
  					<area shape="rect" coords="44,436,448,735" href="/genres" alt="">
  					<area shape="rect" coords="46,762,448,980" href="/contacts/new" alt="">
				</map>
			</div>
			<div class="row current_article_title">
				<h2>最新の投稿記事</h2>
			</div>
			<div class="row current_article_box br50">
			<% @articles.each do |article| %>
				<div class="col-xs-5 top_article_style">
					<div class="row">
						<h3><%= link_to article.title, article_path(article.id), class: "article_title_border" %></h3>
					</div>
					<div class="row img_area_200">
						<% if article.image_id.present? %>
							<%= image_tag "https://inshinmare.s3-ap-northeast-1.amazonaws.com/store/#{article.image_id}" %>
						<% else %>
							<%= image_tag "/images/no_img.png" %>
						<% end %>
					</div>
					<div class="row">
						<span class="glyphicon glyphicon-tag" aria-hidden="true"></span>
						<%= link_to article.genre.name, genre_path(article.genre.id) %>
					</div>
				</div>
			<% end %>
			</div>
		</div>
	</div>
</div>