config/routes.rb
Rails.application.routes.draw do

  get 'tests/test1'
  get 'tests/test2'
  get 'tests/test3'
  root to: 'users#top'
  devise_for :admins
  devise_for :users
  get 'admins/top' => 'admins#top'
  get 'about/top' => 'about#top'
  resources :genres
  resources :articles
  resources :notices
  resources :contacts
  get 'users/top' => 'users#top'
  resources :users, only: [:index, :show, :edit, :update]
  resources :comments, only: [:create, :destroy]
  resources :favgenres, only: [:create, :destroy]
  resources :favarticles, only: [:create, :destroy]
  get 'tests/test1' => 'tests#test1', as: 'test1'
  get 'tests/test2' => 'tests#test2', as: 'test2'
  get 'tests/test3' => 'tests#test3', as: 'test3'
  get 'versions/0_1_1' => 'versions#ver0_1_1', as: 'v0_1_1'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :genre
  has_many :favarticles, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  attachment :image
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :user
end

app/models/favarticle.rb
class Favarticle < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/favgenre.rb
class Favgenre < ApplicationRecord
  belongs_to :user
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
  belongs_to :user
  has_many :articles, dependent: :destroy
  has_many :favgenres, dependent: :destroy

  validates :name, length: { in: 1..10 }, uniqueness: true
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favgenres, dependent: :destroy
  has_many :favarticles, dependent: :destroy
  has_many :genres
  has_many :articles, dependent: :destroy
  has_many :contact
  attachment :image
end

app/models/version.rb
class Version < ApplicationRecord
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_admin!, only:[:destroy]

  def search
    if params[:genre_search].present?
      @genres = Genre.where('name_kana LIKE ?', "%#{params[:genre_search]}%")
    else
      @genres = Genre.all.order(created_at: :desc).take(4)
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.ip = request.env["HTTP_X_FORWARDED_FOR"] || request.remote_ip
    if user_signed_in?
      @article.user_id = current_user.id
    else
    end
    if @article.save
      redirect_to articles_path, notice: '新しく記事を作成しました！'
    else
      render action: :new
    end
  end

  def update
    @article = Article.find(params[:id])
  end

  def index
    search
    if params[:gen].present?
      @articles = Article.where(genre_id: params[:gen]).includes(:genre).page(params[:page]).per(10)
    else
      @articles = Article.all.order(created_at: :desc).includes(:genre).page(params[:page]).per(10)
    end
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.order(created_at: :asc)
    if @article.user.present?
      @user = @article.user
    else
    end
    @genre = @article.genre
    @comment = Comment.new
    if user_signed_in?
      if @favarticle = Favarticle.exists?(user_id: current_user.id, article_id: @article.id)
        @favarticle = Favarticle.find_by(user_id: current_user.id, article_id: @article.id)
      else
        @favarticle = Favarticle.new
      end
    end
  end

  def edit
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to admins_top_path
  end

  private
  def article_params
    params.require(:article).permit(:genre_id, :user_id, :title, :explain, :image, :ip)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/favgenres_helper.rb
module FavgenresHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<div class="row">
	<div class="col-xs-3">
		<%= render 'shared/side_genre' %>
	</div>
	<div class="col-xs-9">
		<h1>最新記事一覧</h1>
		<div class="row br50">
		<% @articles.each do |article| %>
			<div class="col-xs-3">
				<div class="row">
					<p class="font20"><%= link_to article.title, article_path(article.id) %></p>
				</div>
				<div class="row img_area_200 index_item">
					<% if article.image_id.present? %>
						<%= image_tag "https://inshinmare.s3-ap-northeast-1.amazonaws.com/store/#{article.image_id}" %>
					<% else %>
						<%= image_tag "/images/no_img.png" %>
					<% end %>
				</div>
				<div class="row br20">
					<span class="glyphicon glyphicon-tag" aria-hidden="true"></span><%= link_to article.genre.name, genre_path(article.genre.id) %>
				</div>
				<div class="row br20">
					<%= article.explain[0...10] %>...
				</div>
			</div>
		<% end %>
		</div>
		<div class="row br20">
			<%= paginate @articles %>
		</div>
	</div>
</div>

app/views/articles/new.html.erb
<h1>新規記事投稿</h1>
<%= form_with model: @article do |f| %>
<div class="row">
	<div class="col-xs-2">
		<%= f.label :title, "タイトル" %>
	</div>
	<div class="col-xs-4">
		<%= f.text_field :title %>
	</div>
</div>
<div class="row">
	<div class="col-xs-2">
		<%= f.label :image, "画像(任意)" %>
	</div>
	<div class="col-xs-4">
		<%= f.attachment_field :image %>
	</div>
</div>
<div class="row">
	<div class="col-xs-2">
		<%= f.label :genre_id, "ジャンル選択" %>

	</div>
	<div class="col-xs-4">
		<%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "ジャンル選択" %>
	</div>
</div>
<div class="row">
	<div class="col-xs-2">
		<%= f.label :explain, "本文" %>
	</div>
	<div class="col-xs-4">
		<%= f.text_area :explain %>
<div class="row">
	<%= f.submit "投稿", class: "btn btn-danger" %>
</div>
<% end %>

app/views/articles/show.html.erb
<div class="row">
	<div class="col-xs-5">
		<div class="row">
			<div class="col-xs-2"></div>
			<div class="col-xs-10">
				<!-- ここにお気に入りやプロフィール等 -->
				<% if @user.present? %>
					<div class="row">
						<h3>
							この記事を書いた人のプロフィール
						</h3>
					</div>
					<div class="row br50">
						<div class="col-xs-1"></div>
						<div class="col-xs-11">
							<p><span class="font20"><%= @user.name %></span>　さん</p>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-5">
						<% if @user.image_id.present? %>
							<%= image_tag "https://inshinmare.s3-ap-northeast-1.amazonaws.com/store/#{@user.image_id}", size: "100x100" %>
						<% else %>
							<%= image_tag "/images/no_img.png" %>
						<% end %>
						</div>
						<% if @user.introduction.present? %>
							<div class="col-xs-7 word_return">
								<%= @user.introduction %>
							</div>
						<% else %>
							<div class="col-xs-7">
							</div>
						<% end %>
					</div>
				<% else %>
					<div class="row header_line_height">
						<h3>
							匿名のユーザー投稿
						</h3>
						<p>
							<%= link_to "ユーザー登録", new_user_registration_path %>すれば投稿したときにプロフィールが掲載されます。
						</p>
					</div>
				<% end %>
			</div>
		</div>
	</div>
	<div class="col-xs-5">
		<div class="row">
			<h1><%= @article.title %></h1>
			<p><span class="glyphicon glyphicon-tag" aria-hidden="true"></span><%=link_to @article.genre.name, genre_path(@article.genre.id) %></p>
		</div>
		<div class="row">
			<%= @article.explain %>
		</div>
		<div class="row img_area_200">
			<% if @article.image_id.present? %>
				<%= image_tag "https://inshinmare.s3-ap-northeast-1.amazonaws.com/store/#{@article.image_id}" %>
			<% else %>
				<%= image_tag "/images/no_img.png" %>
			<% end %>
		</div>
		<!-- ここからコメント -->
		<% if @comments.present? %>
			<div class="row">
				<h3>コメント一覧(<%= @comments.count %>件)</h3>
			</div>
			<div class="row">
				<% @comments.each_with_index do |comment, cid| %>
				<div class="row comment_box br20">
					<div class="col-xs-2">
						<% if comment.image_id.present? %>
							<%= image_tag "https://inshinmare.s3-ap-northeast-1.amazonaws.com/store/#{comment.image_id}" %>
						<% else %>
							<%= image_tag "/images/no_img.png" %>
						<% end %>
					</div>
					<div class="col-xs-1">
						<p><b><%= cid + 1 %></b></p>
					</div>
					<div class="col-xs-6">
						<div class="row">
							<% if comment.name.present? %>
								<b><%= comment.name %></b>
							<% else %>
							<% end %>
						</div>
						<div class="row">
							<%= comment.explain %>
						</div>
					</div>
					<% if user_signed_in? %>
						<% if @article.user == current_user %>
							<div class="col-xs-2">
								<%= link_to "削除", comment_path, method: :delete, class: "btn btn-danger" %>
							</div>
						<% end %>
					<% end %>
				</div>
				<% end %>
			</div>
		<% else %>
			<div class="row">
				<h2>コメントなし</h2>
			</div>
		<% end %>
		<div class="row">
			<div class="row">
				<h3>新規コメントフォーム</h3>
			</div>
			<%= form_with model: @comment, url: { controller: "comments", action: "create"} do |f| %>
				<div class="row">
					<div class="col-xs-3">
						<%= f.label :name, "名前orタイトル" %>
					</div>
					<div class="col-xs-3">
						<%= f.text_field :name, default: "名無し" %>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-3">
						<%= f.label :image, "画像(あれば)" %>
					</div>
					<div class="col-xs-3">
						<%= f.attachment_field :image, class: "br20" %>
					</div>
				</div>
				<div class="row br20">
					<div class="col-xs-3">
						<%= f.label :explain, "コメント本文" %>
					</div>
					<div class="col-xs-3">
						<%= f.text_area :explain %>
					</div>
				</div>
				<div class="row br20">
					<% if user_signed_in? %>
						<%= f.hidden_field :user_id, :value => current_user.id %>
					<% end %>
					<%= f.hidden_field :article_id, :value => @article.id %>
					<%= f.submit "投稿", class: "btn btn-success" %>
				</div>
			<% end %>
		</div>
	</div>
</div>